In [1]:
import pandas as pd
import plotly.graph_objects as go

In [2]:
import os
print(os.getcwd())

d:\DS_Projects_trip\Sprint7_project\notebooks

In [3]:
# Leer datos desde el archivo CSV
car_data = pd.read_csv("../data/vehicles_us.csv")

In [11]:
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [10]:
car_data.describe()

,price,model_year,cylinders,odometer,is_4wd,days_listed
count,51525.000000,47906.000000,46265.000000,43633.000000,25572.0,51525.00000
mean,12132.464920,2009.750470,6.125235,115553.461738,1.0,39.55476
std,10040.803015,6.282065,1.660360,65094.611341,0.0,28.20427
min,1.000000,1908.000000,3.000000,0.000000,1.0,0.00000
25%,5000.000000,2006.000000,4.000000,70000.000000,1.0,19.00000
50%,9000.000000,2011.000000,6.000000,113000.000000,1.0,33.00000
75%,16839.000000,2014.000000,8.000000,155000.000000,1.0,53.00000
max,375000.000000,2019.000000,12.000000,990000.000000,1.0,271.00000

In [8]:
car_data.sample(10)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
22645,15945,2009.0,cadillac escalade,excellent,8.0,gas,143638.0,automatic,SUV,red,1.0,2019-03-25,12
38708,15000,2009.0,ram 3500,good,6.0,diesel,258000.0,automatic,truck,white,1.0,2019-03-17,19
23661,5900,NaN,chevrolet impala,good,6.0,gas,NaN,automatic,sedan,NaN,NaN,2019-03-01,99
23018,7100,2015.0,kia soul,excellent,4.0,gas,97500.0,automatic,hatchback,green,NaN,2018-12-28,18
39383,18985,2010.0,toyota tacoma,excellent,6.0,gas,132925.0,automatic,pickup,white,1.0,2018-06-06,40
2683,6600,2000.0,toyota 4runner,good,6.0,gas,180.0,automatic,SUV,NaN,1.0,2018-05-22,79
17611,4700,2013.0,chevrolet impala,excellent,NaN,gas,106000.0,automatic,sedan,NaN,NaN,2018-09-18,18
42038,13000,2009.0,dodge grand caravan,good,6.0,gas,97000.0,automatic,mini-van,white,NaN,2019-01-09,36
21009,18990,2015.0,ford f-250 sd,good,8.0,gas,134794.0,automatic,truck,blue,1.0,2019-04-11,40
5054,25942,2018.0,ford edge,excellent,4.0,gas,19887.0,automatic,SUV,black,1.0,2018-08-06,23

In [9]:
car_data.columns

Index(['price', 'model_year', 'model', 'condition', 'cylinders', 'fuel',
       'odometer', 'transmission', 'type', 'paint_color', 'is_4wd',
       'date_posted', 'days_listed'],
      dtype='str')

In [5]:
import plotly.io as pio
pio.renderers.default = "browser"
# Crear un histograma utilizando plotly.graph_objets
# Se crea una figura vacia y luego se añade un rastro de histograma

fig = go.Figure(data=[go.Histogram(x=car_data["odometer"])])

# Opcional: Puedes añadir un titulo al grafico si o deseas

fig.update_layout(title_text="Distribucion del Odometro")

# Mostrar el grafico Plotly

fig.show()

In [6]:
# Crear un scatter plot utilizando plotly.graph_objects
# Se crea una figura vacía y luego se añade un rastro de scatter
fig = go.Figure(data=[go.Scatter(x=car_data['odometer'], y=car_data['price'], mode='markers')])

# Opcional: Puedes añadir un título al gráfico si lo deseas
fig.update_layout(title_text='Relación entre Odómetro y Precio')

# Mostrar el gráfico Plotly
fig.show()